import type { MiniCrosswordPuzzle } from "@/domain/miniCrossword/types";

export const miniCrosswordPuzzles: MiniCrosswordPuzzle[] = [
  {
    id: "wedding-01",
    title: "Wedding Mini #1",
    grid: {
      rows: 5,
      columns: 5,
      solution: ["##GET", "#DEAR", "MARRY", "ARMS#", "YES##"],
    },
    entries: [
      {
        number: 1,
        direction: "across",
        clue: "Understand, as a joke",
        answer: "GET",
        cells: [
          { row: 0, column: 2 },
          { row: 0, column: 3 },
          { row: 0, column: 4 },
        ],
      },
      {
        number: 4,
        direction: "across",
        clue: "Term of affection",
        answer: "DEAR",
        cells: [
          { row: 1, column: 1 },
          { row: 1, column: 2 },
          { row: 1, column: 3 },
          { row: 1, column: 4 },
        ],
      },
      {
        number: 5,
        direction: "across",
        clue: "Tie the knot",
        answer: "MARRY",
        cells: [
          { row: 2, column: 0 },
          { row: 2, column: 1 },
          { row: 2, column: 2 },
          { row: 2, column: 3 },
          { row: 2, column: 4 },
        ],
      },
      {
        number: 6,
        direction: "across",
        clue: "Things wrapped around someone in a hug",
        answer: "ARMS",
        cells: [
          { row: 3, column: 0 },
          { row: 3, column: 1 },
          { row: 3, column: 2 },
          { row: 3, column: 3 },
        ],
      },
      {
        number: 7,
        direction: "across",
        clue: "Answer hoped for after “Will you marry me?”",
        answer: "YES",
        cells: [
          { row: 4, column: 0 },
          { row: 4, column: 1 },
          { row: 4, column: 2 },
        ],
      },
      {
        number: 1,
        direction: "down",
        clue: "Things partners may share after one gets a cold",
        answer: "GERMS",
        cells: [
          { row: 0, column: 2 },
          { row: 1, column: 2 },
          { row: 2, column: 2 },
          { row: 3, column: 2 },
          { row: 4, column: 2 },
        ],
      },
      {
        number: 2,
        direction: "down",
        clue: "What “I love you” might be whispered into",
        answer: "EARS",
        cells: [
          { row: 0, column: 3 },
          { row: 1, column: 3 },
          { row: 2, column: 3 },
          { row: 3, column: 3 },
        ],
      },
      {
        number: 3,
        direction: "down",
        clue: "Give a relationship another shot",
        answer: "TRY",
        cells: [
          { row: 0, column: 4 },
          { row: 1, column: 4 },
          { row: 2, column: 4 },
        ],
      },
      {
        number: 4,
        direction: "down",
        clue: "Challenge for a playful date night",
        answer: "DARE",
        cells: [
          { row: 1, column: 1 },
          { row: 2, column: 1 },
          { row: 3, column: 1 },
          { row: 4, column: 1 },
        ],
      },
      {
        number: 5,
        direction: "down",
        clue: "Popular month for spring weddings",
        answer: "MAY",
        cells: [
          { row: 2, column: 0 },
          { row: 3, column: 0 },
          { row: 4, column: 0 },
        ],
      },
    ],
  },
  {
    id: "wedding-02",
    title: "How Well Do You Know Us?",
    grid: {
      rows: 7,
      columns: 7,
      solution: [
        "T#BUBU#",
        "R#A####",
        "I#N####",
        "VEGGIES",
        "I##O#Y#",
        "ALSO#E#",
        "###DUDU",
      ],
    },
    entries: [
      {
        number: 2,
        direction: "across",
        clue: "Her nickname from him",
        answer: "BUBU",
        cells: [
          { row: 0, column: 2 },
          { row: 0, column: 3 },
          { row: 0, column: 4 },
          { row: 0, column: 5 },
        ],
      },
      {
        number: 3,
        direction: "across",
        clue: "Finish her catchphrase: “Eat yo ___”",
        answer: "VEGGIES",
        cells: [
          { row: 3, column: 0 },
          { row: 3, column: 1 },
          { row: 3, column: 2 },
          { row: 3, column: 3 },
          { row: 3, column: 4 },
          { row: 3, column: 5 },
          { row: 3, column: 6 },
        ],
      },
      {
        number: 6,
        direction: "across",
        clue: "In addition",
        answer: "ALSO",
        cells: [
          { row: 5, column: 0 },
          { row: 5, column: 1 },
          { row: 5, column: 2 },
          { row: 5, column: 3 },
        ],
      },
      {
        number: 7,
        direction: "across",
        clue: "His nickname from her",
        answer: "DUDU",
        cells: [
          { row: 6, column: 3 },
          { row: 6, column: 4 },
          { row: 6, column: 5 },
          { row: 6, column: 6 },
        ],
      },
      {
        number: 1,
        direction: "down",
        clue: "A favorite kind of game night",
        answer: "TRIVIA",
        cells: [
          { row: 0, column: 0 },
          { row: 1, column: 0 },
          { row: 2, column: 0 },
          { row: 3, column: 0 },
          { row: 4, column: 0 },
          { row: 5, column: 0 },
        ],
      },
      {
        number: 2,
        direction: "down",
        clue: "Sudden loud noise",
        answer: "BANG",
        cells: [
          { row: 0, column: 2 },
          { row: 1, column: 2 },
          { row: 2, column: 2 },
          { row: 3, column: 2 },
        ],
      },
      {
        number: 4,
        direction: "down",
        clue: "Not bad",
        answer: "GOOD",
        cells: [
          { row: 3, column: 3 },
          { row: 4, column: 3 },
          { row: 5, column: 3 },
          { row: 6, column: 3 },
        ],
      },
      {
        number: 5,
        direction: "down",
        clue: "What she did to a certain phone screen on the train",
        answer: "EYED",
        cells: [
          { row: 3, column: 5 },
          { row: 4, column: 5 },
          { row: 5, column: 5 },
          { row: 6, column: 5 },
        ],
      },
    ],
  },
];
